// Code generated by mockery v2.20.0. DO NOT EDIT.

package controller

import (
	entities "github.com/facuellarg/order/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockControllerOrderI is an autogenerated mock type for the ControllerOrderI type
type MockControllerOrderI struct {
	mock.Mock
}

type MockControllerOrderI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControllerOrderI) EXPECT() *MockControllerOrderI_Expecter {
	return &MockControllerOrderI_Expecter{mock: &_m.Mock}
}

// CompleteOrder provides a mock function with given fields: _a0
func (_m *MockControllerOrderI) CompleteOrder(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockControllerOrderI_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type MockControllerOrderI_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - _a0 string
func (_e *MockControllerOrderI_Expecter) CompleteOrder(_a0 interface{}) *MockControllerOrderI_CompleteOrder_Call {
	return &MockControllerOrderI_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder", _a0)}
}

func (_c *MockControllerOrderI_CompleteOrder_Call) Run(run func(_a0 string)) *MockControllerOrderI_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockControllerOrderI_CompleteOrder_Call) Return(_a0 error) *MockControllerOrderI_CompleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockControllerOrderI_CompleteOrder_Call) RunAndReturn(run func(string) error) *MockControllerOrderI_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrderEvent provides a mock function with given fields: _a0
func (_m *MockControllerOrderI) CreateOrderEvent(_a0 entities.CreateOrderRequest) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.CreateOrderRequest) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entities.CreateOrderRequest) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entities.CreateOrderRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControllerOrderI_CreateOrderEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderEvent'
type MockControllerOrderI_CreateOrderEvent_Call struct {
	*mock.Call
}

// CreateOrderEvent is a helper method to define mock.On call
//   - _a0 entities.CreateOrderRequest
func (_e *MockControllerOrderI_Expecter) CreateOrderEvent(_a0 interface{}) *MockControllerOrderI_CreateOrderEvent_Call {
	return &MockControllerOrderI_CreateOrderEvent_Call{Call: _e.mock.On("CreateOrderEvent", _a0)}
}

func (_c *MockControllerOrderI_CreateOrderEvent_Call) Run(run func(_a0 entities.CreateOrderRequest)) *MockControllerOrderI_CreateOrderEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.CreateOrderRequest))
	})
	return _c
}

func (_c *MockControllerOrderI_CreateOrderEvent_Call) Return(_a0 string, _a1 error) *MockControllerOrderI_CreateOrderEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControllerOrderI_CreateOrderEvent_Call) RunAndReturn(run func(entities.CreateOrderRequest) (string, error)) *MockControllerOrderI_CreateOrderEvent_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockControllerOrderI interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockControllerOrderI creates a new instance of MockControllerOrderI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockControllerOrderI(t mockConstructorTestingTNewMockControllerOrderI) *MockControllerOrderI {
	mock := &MockControllerOrderI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
